# Generated by Django 4.2.17 on 2025-05-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
